# Generated by Django 4.2.1 on 2023-05-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=164)),
                ('subtitulo', models.CharField(max_length=164)),
                ('cuerpo', models.CharField(max_length=254)),
                ('autor', models.CharField(max_length=164)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
